# touch docker compose
services:
  web:
    image: my_app
    ports: 
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /home/my_app/  # Set the working directory
    command: >
      sh -c 'carton exec -- perl my_app/utils/db-migrate.pl && carton exec -- morbo my_app/script/my_app' 
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
    networks:
      - my-app-net
  database:
    build:
      context: .
      dockerfile: DockerfileDB
    container_name: circle_ci_test_repo-database-1
    ports: 
      - "3306:3306"
    env_file:
      - .env
    networks:
      - my-app-net
    healthcheck:
      test: ["CMD", "./healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
networks:
 my-app-net:
