# touch docker compose
services:
  web:
    image: my_app
    ports: 
      - "3000:3000"
    build:
      context: .
      dockerfile: DockerfileTest
    working_dir: /home/my_app/  # Set the working directory
    command: >
      sh -c 'carton exec -- morbo my_app/script/my_app' 
    env_file:
      - .env
    # volumes:
    #   - ${PWD}/my_app:/home/my_app/my_app:ro
      # - ${PWD}/.env:/home/my_app/.env:ro
    depends_on:
      database:
        condition: service_healthy
    networks:
      - my-app-net
  database:
    image: mariadb
    container_name: circle_ci_test_repo-database-1
    ports: 
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes: 
      - maria-data:/var/lib/mysql
      - ./my_app/migrations:/docker-entrypoint-initdb.d
    networks:
      - my-app-net
    healthcheck:
      test: ["CMD-SHELL", "mariadb -h127.0.0.1 -umyuser -ppassword -e 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
volumes:
  maria-data:
    name: maria_data_global

networks:
 my-app-net:

