# touch docker compose
services:
  web:
    image: my_app
    ports: 
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /home/my_app  # Set the working directory
    env_file:
      - .env
    volumes:
      - ./my_app:/home/my_app/my_app:ro
      - ./.env:/home/my_app/.env:ro
    depends_on:
      database:
        condition: service_healthy
    networks:
      - my-app-net
  database:
    image: mariadb
    ports: 
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes: 
      - maria-data:/var/lib/mysql
      - ./my_app/migrations:/docker-entrypoint-initdb.d
    networks:
      - my-app-net
    healthcheck:
      test: ["CMD-SHELL", "mariadb -h127.0.0.1 -uroot -e 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s


volumes:
  maria-data:

networks:
 my-app-net:

