version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.0.2
  aws-cli: circleci/aws-cli@4.1
  ecr-scan-orb: tusker-direct/ecr-scan-orb@1.0

parameters:
  service-name:
    type: string
    default: "circleci-test"
  image-repo-name:
    type: string
    default: "tusker-direct/circleci-test"
  image-name:
    type: string
    default: "${AWS_ECR_REGISTRY_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/tusker-direct/redis_test"
  image-tag:
    type: string
    default: "${CIRCLE_SHA1}"
  oidc-role-arn:
    type: string
    default: "arn:aws:iam::${AWS_ACCOUNT_ID}:role/CircleCI_Role"

executors:
  perl_test_env:
    docker:
      - image: perl:5.32

commands:
  aws_auth:
    parameters:
      role_arn:
        type: string
        default: << pipeline.parameters.oidc-role-arn >>
    steps:
      - aws-cli/setup:
          profile_name: CircleCI
          role_arn: << parameters.role_arn >>

jobs:
  build:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - aws-ecr/build_and_push_image:
          auth:
            - aws-cli/setup:
                profile_name: CircleCI
                role_arn: << pipeline.parameters.oidc-role-arn >>
          profile_name: CircleCI
          create_repo: true
          path: .
          platform: linux/amd64
          push_image: true
          repo: tusker-direct/<< pipeline.parameters.service-name >>
          tag: "${CIRCLE_SHA1}"
          extra_build_args: --provenance false
          setup_remote_docker: true
          remote_docker_layer_caching: true

  style_check:
    executor: perl_test_env
    steps:
      - checkout
      - run:
          name: Install Cpanm
          command: curl -L http://cpanmin.us | perl - App::cpanminus
      - run:
          name: Install Perl::Tidy
          command: cpanm Perl::Tidy --no-test
      - run:
          name: Run perltidy check
          command: |
            FILES=$(find $(pwd) -type f \( -name "*.pl" -o -name "*.pm" -o -name "*.t" \) -mtime -14)
            if [ -z "$FILES" ]; then
              echo "No Perl files found to check!"
              exit 1
            fi
            echo "Found files:"
            echo "$FILES"
            echo ""
            echo "Checking Perl files formatting..."
            echo "--------------------------------"
            JOINED_FILES=$(printf "%s " "${FILES[@]}")
            echo "${JOINED_FILES}"
            perltidy -pro=.perltidyrc --assert-tidy -st -se ${JOINED_FILES}

  perlcritic:
    executor: perl_test_env
    steps:
      - checkout
      - run:
          name: Install Cpanm
          command: curl -L http://cpanmin.us | perl - App::cpanminus
      - run:
          name: Install Perl::Critic
          command: cpanm Perl::Critic
      - run:
          name: Run perlcritic check
          command: |
            FILES=$(find $(pwd) -type f \( -name "*.pl" -o -name "*.pm" -o -name "*.t" \) -mtime -14)
            if [ -z "$FILES" ]; then
              echo "No Perl files found to check!"
              exit 1
            fi
            echo "Found files:"
            echo "$FILES"
            echo ""
            echo "Running Perl::Critic analysis..."
            echo "--------------------------------"
            HAS_ISSUES=0
            for file in $FILES; do
              echo "Analyzing $file..."
              if ! perlcritic --stern "$file"; then
                echo "❌ $file ... has issues"
                HAS_ISSUES=1
              fi
            done
            echo "--------------------------------"
            if [ "$HAS_ISSUES" -eq 1 ]; then
              echo "Some files have code quality issues. Please fix them locally."
              exit 1
            else
              echo "All files passed Perl::Critic analysis!"
            fi

  image_scan:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - aws_auth
      - ecr-scan-orb/scan:
          profile_name: CircleCI
          repository_name: << pipeline.parameters.image-repo-name >>
          image_id: "imageTag=<< pipeline.parameters.image-tag >>"
          security_policy: CRITICAL

  test:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - aws_auth
      - run:
          name: Run tests
          command: |
            echo "Running tests..."
            echo "--------------------------------"
            perl -Ilib t/*.t

  perltidy_check:
    docker:
      - image: perl:5.32
    steps:
      - checkout
      - run:
          name: Install Perl::Tidy
          command: cpan Perl::Tidy
      - run:
          name: Run Perltidy Check
          command: |
            find . -name "*.pl" -o -name "*.pm" -o -name "*.t" | while read file; do
              perltidy -pro=.perltidyrc -b -bext='/' "$file"
              if [ -f "${file}.bak" ]; then
                diff "$file" "${file}.bak" > /dev/null
                if [ $? -ne 0 ]; then
                  echo "Code style issues found in $file"
                  rm "${file}.bak"
                  exit 1
                fi
                rm "${file}.bak"
              fi
            done

workflows:
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - style_check:
          requires:
            - build
      - perlcritic:
          requires:
            - style_check

  build_test_and_push:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - image_scan:
          requires:
            - build
      - test:
          requires:
            - build
      - perltidy_check:
          requires:
            - build
