version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.0.2
  aws-cli: circleci/aws-cli@4.1
  ecr-scan-orb: tusker-direct/ecr-scan-orb@1.0

parameters:
  service-name:
    type: string
    default: "circleci-test"
  image-repo-name:
    type: string
    default: "tusker-direct/circleci-test"
  image-name:
    type: string
    default: "${AWS_ECR_REGISTRY_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/tusker-direct/redis_test"
  image-tag:
    type: string
    default: "${CIRCLE_SHA1}"
  oidc-role-arn:
    type: string
    default: "arn:aws:iam::${AWS_ACCOUNT_ID}:role/CircleCI_Role"

executors:
  perl_test_env:
    docker:
      - image: perl:5.32

commands:
  aws_auth:
    parameters:
      role_arn:
        type: string
        default: << pipeline.parameters.oidc-role-arn >>
    steps:
      - aws-cli/setup:
          profile_name: CircleCI
          role_arn: << parameters.role_arn >>

  install_cpanm:
    steps:
      - run:
          name: Install cpanminus
          command: curl -L http://cpanmin.us | perl - App::cpanminus

  perl_file_finder:
    steps:
      - run:
          name: Find recent Perl files
          command: |
            export FILES=$(find $(pwd)/my_app -type f \( -name "*.pl" -o -name "*.pm" -o -name "*.t" \) -mtime -14)
            echo "$FILES" > perl_files.txt
            if [ -z "$FILES" ]; then
              echo "No Perl files found to check!"
              exit 1
            fi
            echo "Found Perl files:"
            echo "$FILES"

jobs:
  build:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - aws-ecr/build_and_push_image:
          auth:
            - aws-cli/setup:
                profile_name: CircleCI
                role_arn: << pipeline.parameters.oidc-role-arn >>
          profile_name: CircleCI
          create_repo: true
          path: .
          platform: linux/amd64
          push_image: true
          repo: tusker-direct/<< pipeline.parameters.service-name >>
          tag: << pipeline.parameters.image-tag >>
          extra_build_args: --provenance false
          setup_remote_docker: true
          remote_docker_layer_caching: true

  perl_tidy_check:
    executor: perl_test_env
    steps:
      - checkout
      - setup_remote_docker
      - install_cpanm
      - run:
          name: Install Perl::Tidy
          command: cpanm Perl::Tidy --notest
      - perl_file_finder
      - run:
          name: Run perltidy check
          command: |
            perltidy -pro=.perltidyrc --assert-tidy $(cat perl_files.txt)

  perlcritic:
    executor: perl_test_env
    steps:
      - checkout
      - install_cpanm
      - run:
          name: Install Perl::Critic
          command: cpanm Perl::Critic --notest
      - perl_file_finder
      - run:
          name: Run perlcritic check
          command: |
            perlcritic --profile-strictness fatal $(cat perl_files.txt)

  image_scan:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - aws_auth
      - ecr-scan-orb/scan:
          profile_name: CircleCI
          repository_name: << pipeline.parameters.image-repo-name >>
          image_id: "imageTag=<< pipeline.parameters.image-tag >>"
          security_policy: CRITICAL

  test:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker
      - aws_auth
      - run:
          name: Build and run tests
          command: |
            echo "PWD: $(pwd)"
            file .env || true
            ls -la
            docker compose build
            docker compose up -d
            docker exec -it project-web-1 bash -c "cd my_app && carton exec -- prove -v t/"

workflows:
  build_test_and_push:
    jobs:
      - build:
          filters:
            branches:
              only: [main]
      - perl_tidy_check:
          requires: [build]
      - perlcritic:
          requires: [build]
      - image_scan:
          requires: [build]
      - test:
          requires: [build]
